"""baseline schema

Revision ID: ec1d8329475e
Revises: 
Create Date: 2026-07-27 05:55:47.354994
"""
from alembic import op
import sqlalchemy as sa


revision = 'ec1d8329475e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organisation_id', sa.String(length=32), nullable=False),
    sa.Column('shop_id', sa.String(length=32), nullable=True),
    sa.Column('actor_type', sa.String(length=20), nullable=False),
    sa.Column('actor_user_id', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=160), nullable=False),
    sa.Column('resource_type', sa.String(length=120), nullable=False),
    sa.Column('resource_id', sa.String(length=32), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_organisation_id'), ['organisation_id'], unique=False)
        batch_op.create_index('ix_audit_org_created', ['organisation_id', 'created_at'], unique=False)

    op.create_table('demo_scenarios',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('seed_version', sa.Integer(), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('organisations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('plan_code', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('rule_definitions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('default_severity', sa.String(length=20), nullable=False),
    sa.Column('is_system_rule', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rule_definitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rule_definitions_code'), ['code'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=160), nullable=True),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('webhook_events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organisation_id', sa.String(length=32), nullable=False),
    sa.Column('shop_id', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('external_webhook_id', sa.String(length=255), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('hmac_valid', sa.Boolean(), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('headers_redacted', sa.JSON(), nullable=False),
    sa.Column('processing_status', sa.String(length=30), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webhook_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhook_events_idempotency_key'), ['idempotency_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_webhook_events_organisation_id'), ['organisation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhook_events_shop_id'), ['shop_id'], unique=False)

    op.create_table('commerce_events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organisation_id', sa.String(length=32), nullable=False),
    sa.Column('shop_id', sa.String(length=32), nullable=False),
    sa.Column('webhook_event_id', sa.String(length=32), nullable=True),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('source_system', sa.String(length=120), nullable=False),
    sa.Column('entity_type', sa.String(length=120), nullable=False),
    sa.Column('entity_external_id', sa.String(length=255), nullable=False),
    sa.Column('before_state', sa.JSON(), nullable=True),
    sa.Column('after_state', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('normalized_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['webhook_event_id'], ['webhook_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('commerce_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_commerce_events_organisation_id'), ['organisation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_commerce_events_shop_id'), ['shop_id'], unique=False)

    op.create_table('demo_resets',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('demo_scenario_id', sa.String(length=32), nullable=True),
    sa.Column('organisation_id', sa.String(length=32), nullable=False),
    sa.Column('shop_id', sa.String(length=32), nullable=True),
    sa.Column('requested_by_user_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['demo_scenario_id'], ['demo_scenarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('demo_resets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_demo_resets_organisation_id'), ['organisation_id'], unique=False)

    op.create_table('memberships',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organisation_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('invited_by_user_id', sa.String(length=32), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organisation_id', 'user_id')
    )
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memberships_organisation_id'), ['organisation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memberships_user_id'), ['user_id'], unique=False)

    op.create_table('rule_versions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('rule_definition_id', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('implementation_reference', sa.Text(), nullable=False),
    sa.Column('remediation_templates', sa.JSON(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('active_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['rule_definition_id'], ['rule_definitions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_definition_id', 'version')
    )
    with op.batch_alter_table('rule_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rule_versions_rule_definition_id'), ['rule_definition_id'], unique=False)

    op.create_table('shops',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organisation_id', sa.String(length=32), nullable=False),
    sa.Column('platform', sa.String(length=30), nullable=False),
    sa.Column('shop_domain', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=180), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shops', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shops_organisation_id'), ['organisation_id'], unique=False)

    op.create_table('connectors',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organisation_id', sa.String(length=32), nullable=False),
    sa.Column('shop_id', sa.String(length=32), nullable=True),
    sa.Column('connector_type', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.Column('secret_reference', sa.Text(), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_code', sa.String(length=100), nullable=True),
    sa.Column('last_error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('connectors', schema=None) as batch_op:
        batch_op.create_index('ix_connectors_org_type_status', ['organisation_id', 'connector_type', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_connectors_organisation_id'), ['organisation_id'], unique=False)

    op.create_table('runs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organisation_id', sa.String(length=32), nullable=False),
    sa.Column('shop_id', sa.String(length=32), nullable=False),
    sa.Column('commerce_event_id', sa.String(length=32), nullable=True),
    sa.Column('trigger_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('correlation_id', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_code', sa.String(length=100), nullable=True),
    sa.Column('failure_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_by', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['commerce_event_id'], ['commerce_events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_runs_organisation_id'), ['organisation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_runs_shop_id'), ['shop_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_runs_status'), ['status'], unique=False)

    op.create_table('context_snapshots',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('datahub_gms_url', sa.String(length=255), nullable=False),
    sa.Column('datahub_version', sa.String(length=40), nullable=True),
    sa.Column('root_urn', sa.Text(), nullable=False),
    sa.Column('lineage_edges', sa.Integer(), nullable=False),
    sa.Column('max_hops', sa.Integer(), nullable=False),
    sa.Column('assets', sa.JSON(), nullable=False),
    sa.Column('tool_trace', sa.JSON(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('context_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_context_snapshots_run_id'), ['run_id'], unique=False)

    op.create_table('datahub_connections',
    sa.Column('connector_id', sa.String(length=32), nullable=False),
    sa.Column('gms_url', sa.Text(), nullable=False),
    sa.Column('mcp_transport', sa.String(length=20), nullable=False),
    sa.Column('mcp_server_version', sa.String(length=40), nullable=True),
    sa.Column('datahub_version', sa.String(length=40), nullable=True),
    sa.Column('mutation_enabled', sa.Boolean(), nullable=False),
    sa.Column('service_account_name', sa.String(length=160), nullable=True),
    sa.Column('secret_reference', sa.Text(), nullable=True),
    sa.Column('last_read_test_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_write_test_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['connector_id'], ['connectors.id'], ),
    sa.PrimaryKeyConstraint('connector_id')
    )
    op.create_table('datahub_writebacks',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('operations', sa.JSON(), nullable=False),
    sa.Column('verification_result', sa.JSON(), nullable=False),
    sa.Column('document_urn', sa.Text(), nullable=True),
    sa.Column('tool_trace', sa.JSON(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('datahub_writebacks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_datahub_writebacks_run_id'), ['run_id'], unique=False)

    op.create_table('generated_artifacts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('remediation_plan_id', sa.String(length=32), nullable=True),
    sa.Column('artifact_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('workspace_reference', sa.Text(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('combined_diff', sa.Text(), nullable=False),
    sa.Column('files', sa.JSON(), nullable=False),
    sa.Column('skipped', sa.JSON(), nullable=False),
    sa.Column('rejected', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('generated_artifacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_generated_artifacts_run_id'), ['run_id'], unique=False)

    op.create_table('github_connections',
    sa.Column('connector_id', sa.String(length=32), nullable=False),
    sa.Column('installation_id', sa.Integer(), nullable=True),
    sa.Column('account_login', sa.String(length=255), nullable=True),
    sa.Column('repository_owner', sa.String(length=255), nullable=True),
    sa.Column('repository_name', sa.String(length=255), nullable=True),
    sa.Column('default_branch', sa.String(length=255), nullable=False),
    sa.Column('repository_allowlist', sa.JSON(), nullable=False),
    sa.Column('dry_run_enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['connectors.id'], ),
    sa.PrimaryKeyConstraint('connector_id')
    )
    op.create_table('incidents',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organisation_id', sa.String(length=32), nullable=False),
    sa.Column('shop_id', sa.String(length=32), nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('owner_user_id', sa.String(length=255), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.create_index('ix_incidents_org_status_severity', ['organisation_id', 'status', 'severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_organisation_id'), ['organisation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_shop_id'), ['shop_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_status'), ['status'], unique=False)

    op.create_table('pull_requests',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('repository_full_name', sa.String(length=255), nullable=True),
    sa.Column('branch_name', sa.String(length=255), nullable=False),
    sa.Column('commit_sha', sa.String(length=64), nullable=True),
    sa.Column('external_pr_number', sa.Integer(), nullable=True),
    sa.Column('external_pr_url', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pull_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pull_requests_run_id'), ['run_id'], unique=False)

    op.create_table('remediation_plans',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('business_impact', sa.Text(), nullable=False),
    sa.Column('proposed_actions', sa.JSON(), nullable=False),
    sa.Column('validation_plan', sa.JSON(), nullable=False),
    sa.Column('rollback_plan', sa.Text(), nullable=False),
    sa.Column('confidence_explanation', sa.Text(), nullable=True),
    sa.Column('plan_source', sa.String(length=30), nullable=False),
    sa.Column('rejected_reason', sa.Text(), nullable=True),
    sa.Column('model_provider', sa.String(length=80), nullable=True),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'version')
    )
    with op.batch_alter_table('remediation_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_remediation_plans_run_id'), ['run_id'], unique=False)

    op.create_table('rule_executions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('rule_version_id', sa.String(length=32), nullable=True),
    sa.Column('rule_code', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('finding_count', sa.Integer(), nullable=False),
    sa.Column('skip_reason', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['rule_version_id'], ['rule_versions.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rule_executions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rule_executions_rule_code'), ['rule_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_rule_executions_run_id'), ['run_id'], unique=False)
        batch_op.create_index('ix_rule_executions_run_status', ['run_id', 'status'], unique=False)

    op.create_table('run_transitions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('from_status', sa.String(length=40), nullable=True),
    sa.Column('to_status', sa.String(length=40), nullable=False),
    sa.Column('transition_reason', sa.Text(), nullable=True),
    sa.Column('actor_type', sa.String(length=20), nullable=False),
    sa.Column('actor_user_id', sa.String(length=32), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('run_transitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_run_transitions_run_id'), ['run_id'], unique=False)

    op.create_table('shopify_connections',
    sa.Column('connector_id', sa.String(length=32), nullable=False),
    sa.Column('shop_id', sa.String(length=32), nullable=True),
    sa.Column('shopify_shop_domain', sa.String(length=255), nullable=False),
    sa.Column('shopify_shop_gid', sa.String(length=255), nullable=True),
    sa.Column('api_version', sa.String(length=20), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('token_reference', sa.Text(), nullable=True),
    sa.Column('installed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('uninstalled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_webhook_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['connector_id'], ['connectors.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('connector_id'),
    sa.UniqueConstraint('shopify_shop_domain')
    )
    op.create_table('validation_runs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('generated_artifact_id', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('environment', sa.String(length=80), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('validation_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_validation_runs_run_id'), ['run_id'], unique=False)

    op.create_table('approvals',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('remediation_plan_id', sa.String(length=32), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('decided_by', sa.String(length=255), nullable=False),
    sa.Column('decided_by_role', sa.String(length=30), nullable=False),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('context_snapshot_checksum', sa.String(length=64), nullable=False),
    sa.Column('plan_checksum', sa.String(length=64), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['remediation_plan_id'], ['remediation_plans.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approvals_run_id'), ['run_id'], unique=False)

    op.create_table('findings',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organisation_id', sa.String(length=32), nullable=False),
    sa.Column('shop_id', sa.String(length=32), nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('rule_code', sa.String(length=120), nullable=False),
    sa.Column('rule_version', sa.Integer(), nullable=False),
    sa.Column('rule_execution_id', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('expected_value', sa.JSON(), nullable=True),
    sa.Column('observed_value', sa.JSON(), nullable=True),
    sa.Column('source_asset_urn', sa.Text(), nullable=True),
    sa.Column('downstream_asset_urn', sa.Text(), nullable=True),
    sa.Column('owner_reference', sa.JSON(), nullable=True),
    sa.Column('customer_impact', sa.Text(), nullable=True),
    sa.Column('business_risk', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('auto_fix_eligible', sa.Boolean(), nullable=False),
    sa.Column('remediation_template', sa.String(length=120), nullable=True),
    sa.Column('target_file', sa.Text(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['rule_execution_id'], ['rule_executions.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_findings_organisation_id'), ['organisation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_rule_code'), ['rule_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_rule_execution_id'), ['rule_execution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_run_id'), ['run_id'], unique=False)
        batch_op.create_index('ix_findings_run_severity', ['run_id', 'severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_shop_id'), ['shop_id'], unique=False)
        batch_op.create_index('ix_findings_shop_status_severity', ['shop_id', 'status', 'severity'], unique=False)

    op.create_table('incident_events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('incident_id', sa.String(length=32), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('actor_type', sa.String(length=20), nullable=False),
    sa.Column('actor_user_id', sa.String(length=255), nullable=True),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incident_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incident_events_incident_id'), ['incident_id'], unique=False)

    op.create_table('finding_incidents',
    sa.Column('finding_id', sa.String(length=32), nullable=False),
    sa.Column('incident_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('finding_id', 'incident_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('finding_incidents')
    with op.batch_alter_table('incident_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incident_events_incident_id'))

    op.drop_table('incident_events')
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.drop_index('ix_findings_shop_status_severity')
        batch_op.drop_index(batch_op.f('ix_findings_shop_id'))
        batch_op.drop_index(batch_op.f('ix_findings_severity'))
        batch_op.drop_index('ix_findings_run_severity')
        batch_op.drop_index(batch_op.f('ix_findings_run_id'))
        batch_op.drop_index(batch_op.f('ix_findings_rule_execution_id'))
        batch_op.drop_index(batch_op.f('ix_findings_rule_code'))
        batch_op.drop_index(batch_op.f('ix_findings_organisation_id'))

    op.drop_table('findings')
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approvals_run_id'))

    op.drop_table('approvals')
    with op.batch_alter_table('validation_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_validation_runs_run_id'))

    op.drop_table('validation_runs')
    op.drop_table('shopify_connections')
    with op.batch_alter_table('run_transitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_run_transitions_run_id'))

    op.drop_table('run_transitions')
    with op.batch_alter_table('rule_executions', schema=None) as batch_op:
        batch_op.drop_index('ix_rule_executions_run_status')
        batch_op.drop_index(batch_op.f('ix_rule_executions_run_id'))
        batch_op.drop_index(batch_op.f('ix_rule_executions_rule_code'))

    op.drop_table('rule_executions')
    with op.batch_alter_table('remediation_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_remediation_plans_run_id'))

    op.drop_table('remediation_plans')
    with op.batch_alter_table('pull_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pull_requests_run_id'))

    op.drop_table('pull_requests')
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incidents_status'))
        batch_op.drop_index(batch_op.f('ix_incidents_shop_id'))
        batch_op.drop_index(batch_op.f('ix_incidents_severity'))
        batch_op.drop_index(batch_op.f('ix_incidents_run_id'))
        batch_op.drop_index(batch_op.f('ix_incidents_organisation_id'))
        batch_op.drop_index('ix_incidents_org_status_severity')

    op.drop_table('incidents')
    op.drop_table('github_connections')
    with op.batch_alter_table('generated_artifacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generated_artifacts_run_id'))

    op.drop_table('generated_artifacts')
    with op.batch_alter_table('datahub_writebacks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_datahub_writebacks_run_id'))

    op.drop_table('datahub_writebacks')
    op.drop_table('datahub_connections')
    with op.batch_alter_table('context_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_context_snapshots_run_id'))

    op.drop_table('context_snapshots')
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_runs_status'))
        batch_op.drop_index(batch_op.f('ix_runs_shop_id'))
        batch_op.drop_index(batch_op.f('ix_runs_organisation_id'))

    op.drop_table('runs')
    with op.batch_alter_table('connectors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_connectors_organisation_id'))
        batch_op.drop_index('ix_connectors_org_type_status')

    op.drop_table('connectors')
    with op.batch_alter_table('shops', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shops_organisation_id'))

    op.drop_table('shops')
    with op.batch_alter_table('rule_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rule_versions_rule_definition_id'))

    op.drop_table('rule_versions')
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memberships_user_id'))
        batch_op.drop_index(batch_op.f('ix_memberships_organisation_id'))

    op.drop_table('memberships')
    with op.batch_alter_table('demo_resets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_demo_resets_organisation_id'))

    op.drop_table('demo_resets')
    with op.batch_alter_table('commerce_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_commerce_events_shop_id'))
        batch_op.drop_index(batch_op.f('ix_commerce_events_organisation_id'))

    op.drop_table('commerce_events')
    with op.batch_alter_table('webhook_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_events_shop_id'))
        batch_op.drop_index(batch_op.f('ix_webhook_events_organisation_id'))
        batch_op.drop_index(batch_op.f('ix_webhook_events_idempotency_key'))

    op.drop_table('webhook_events')
    op.drop_table('users')
    with op.batch_alter_table('rule_definitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rule_definitions_code'))

    op.drop_table('rule_definitions')
    op.drop_table('organisations')
    op.drop_table('demo_scenarios')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_org_created')
        batch_op.drop_index(batch_op.f('ix_audit_logs_organisation_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
