"""Build the static marketing site for Vercel.

The source of truth stays `apps/api/static/marketing/` — the API serves those
same files, so a judge reaching either host sees identical content. This script
only adapts paths for static hosting:

  * the stylesheet moves to `/site.css` (no `/static` mount off the API)
  * `/app` becomes an absolute URL, because the product lives on the VM and
    cannot be served from a CDN

Run it before deploying:  python web/build.py
"""

from __future__ import annotations

import argparse
import json
import os
import re
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "apps" / "api" / "static" / "marketing"
DIST = ROOT / "web" / "dist"

# Where the product actually runs. Overridden once comgu.site resolves.
DEFAULT_APP_URL = os.environ.get("COMGU_APP_URL", "https://app.comgu.site")

PAGES = ["index.html", "datahub.html", "security.html", "open-source.html",
         "catalog.html"]


def adapt(text: str, app_url: str) -> str:
    """Rewrite paths that differ between the API host and static hosting.

    Applies to CSS as well as HTML — `site.css` references the logo through the
    same `/static/marketing/` prefix, so rewriting only the markup would leave
    the header mark broken on Vercel.
    """
    # The API mounts these under /static/marketing; on a CDN they sit at the root.
    text = text.replace("/static/marketing/", "/")
    # Only the app link is absolute; internal marketing routes stay relative so
    # the same markup works on both hosts.
    text = re.sub(r'href="/app"', f'href="{app_url}/app"', text)
    return text


def main() -> int:
    ap = argparse.ArgumentParser(description="Build the Comgu marketing site")
    ap.add_argument("--app-url", default=DEFAULT_APP_URL)
    args = ap.parse_args()

    # Clear the build output without removing `.vercel`. That directory holds
    # the project link, is gitignored, and cannot be regenerated from the repo
    # — deleting it makes the next `vercel deploy` create a brand new project
    # named after this folder ("dist") instead of updating the real one.
    if DIST.exists():
        for child in DIST.iterdir():
            if child.name == ".vercel":
                continue
            shutil.rmtree(child) if child.is_dir() else child.unlink()
    DIST.mkdir(parents=True, exist_ok=True)

    # site.css needs the same path rewriting as the pages — it points at the logo.
    (DIST / "site.css").write_text(
        adapt((SRC / "site.css").read_text(), args.app_url.rstrip("/"))
    )
    for page in PAGES:
        out = adapt((SRC / page).read_text(), args.app_url.rstrip("/"))
        (DIST / page).write_text(out)

    # Brand assets, generated by web/icons.py from comgu-logo/.
    icons = sorted(SRC.glob("*.png"))
    for icon in icons:
        shutil.copy(icon, DIST / icon.name)

    # A judge who loses the VM should still be told what they are looking at.
    (DIST / "404.html").write_text(
        (DIST / "index.html").read_text().replace(
            "<title>Comgu", "<title>Not found — Comgu"
        )
    )

    # The nav links to `/datahub`, not `/datahub.html`, so that the same markup
    # works on the API host where FastAPI routes those paths. Static hosting has
    # to be told to do the same or every nav link outside the homepage 404s.
    (DIST / "vercel.json").write_text(
        json.dumps({"cleanUrls": True, "trailingSlash": False}, indent=2) + "\n"
    )

    print(f"built {len(PAGES) + 3} pages/config + {len(icons)} brand assets into {DIST}")
    print(f"  app links -> {args.app_url}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
